name: make snake_graph
on:
  workflow_dispatch:
jobs:
  build:
    name: snake_graph
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@v3.2.0
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: | 
              dist/snek.svg?palette=github-dark&color_snake=#82aaff&color_dots=#242938,#0b7552,#07a771,#1cc48c,#27e8a7
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: crazy-max/ghaction-github-pages@v3.0.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
